### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by SaifurRahmanMohsin**
Minor typo fix

### CODE REVIEW

**Review by Devsome — APPROVED** [review]

**Comment by Devsome** [comment]
Thanks for the Typo fix, but I don't let this count as a Hacktoberfest merge.

**Comment by SaifurRahmanMohsin** [comment]
@Devsome No issue: after all this is very minor fix. I shall make a larger commit for hacktoberfest merge.

**Comment by Devsome** [comment]
@SaifurRahmanMohsin if you have any Question to any kind of Project just ask me. I love to see people helping at Hacktoberfest

**Comment by SaifurRahmanMohsin** [comment]
Hey @Devsome, I do have a question related to this project: the same translation strings as referred again and again in multiple places. For example: the phrase **web inventory** is referred [here](https://github.com/Devsome/silkroad-laravel/blob/master/resources/lang/en/webinventory.php#L4), [here](https://github.com/Devsome/silkroad-laravel/blob/master/resources/lang/en/auctionshouse.php#L13), [here](https://github.com/Devsome/silkroad-laravel/blob/master/resources/lang/en/sidebar.php#L39) and [here](https://github.com/Devsome/silkroad-laravel/blob/master/resources/lang/en/home.php#L20). These are all within the same language set and are redundant since it's a single project. I found **several** such redundancies and figured that the translation string could be far lesser if these redundancies are removed. Is there any specific reason for this or it's just something accidental that was missed out?

**Comment by Devsome** [comment]
Yes you are right that some strings are repeated. I didn't know at first that so many are similar.
I tried to create an extra translation for each blade.view, so I know exactly which translation is for which file. @SaifurRahmanMohsin

**Comment by SaifurRahmanMohsin** [comment]
Ah, I see. Wouldn't be efficient to remove these repeated translations? I could even make a PR for this if you'd like to see the redundancy removed.

**Comment by SaifurRahmanMohsin** [comment]
Ah, I see. Wouldn't be efficient to remove these repeated translations? I could even make a PR for this if you'd like to see the redundancy removed.

P.S. I understand that it might be easy for you to co-relate translations to the corresponding blade files. However, this goes against the whole DRY principle and also makes the life of translators difficult.

**Comment by Devsome** [comment]
@SaifurRahmanMohsin I see. I also got some problems translating that stuff also. If you have time would be awesome to see the redundancy removed.

**Pull request merged**
